@startuml
'https://plantuml.com/class-diagram

class ReadJSONFile



class ReadJSONFile {
    +int Flag


    + void main()
    +String userInput()
    +productCheck(input, flag, iterator);
}




@enduml